Added reimplementation for pdnsmanager 2

diff --git a/pdns-acme b/pdns-acme
--- a/pdns-acme
+++ b/pdns-acme
@@ -1,144 +1,98 @@
 #!/bin/bash
-#
-#Copyright 2016 Lukas Metzger <developer@lukas-metzger.com>.
-#
-#Licensed under the Apache License, Version 2.0 (the "License");
-#you may not use this file except in compliance with the License.
-#You may obtain a copy of the License at
-#
-#    http://www.apache.org/licenses/LICENSE-2.0
-#
-#Unless required by applicable law or agreed to in writing, software
-#distributed under the License is distributed on an "AS IS" BASIS,
-#WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
-#See the License for the specific language governing permissions and
-#limitations under the License.
 
-
-SD="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
-
-CONFIG=""
-SERVER=""
-PDNSCLIENT=""
-SLEEP=0
-
-function deploy_challenge {
-    local DOMAIN="${1}" TOKEN="${3}"
-
-    "$PDNSCLIENT" -s "$SERVER" -d "_acme-challenge.$DOMAIN" -i "$(get_id "$DOMAIN")" -c "$TOKEN"
-
-    sleep $SLEEP 
+exit_error() {
+    echo "ERROR: ${1}" >&2
+    exit 1
 }
 
-function clean_challenge {
-    local DOMAIN="${1}" TOKEN="${3}"
+init() {
+    cd pdns-client
 
-    "$PDNSCLIENT" -s "$SERVER" -d "_acme-challenge.$DOMAIN" -i "$(get_id "$DOMAIN")" -c "none"
+    if [ ! -f pdns.public.pem ]
+    then
+        ./pdns-keygen
+    fi
+
+    cd ..
+
+    cd dehydrated
+
+    ./dehydrated --register --accept-terms
+
+    cd ..
 }
 
-function deploy_cert {
-    local DOMAIN="${1}" KEYFILE="${2}" CERTFILE="${3}" CHAINFILE="${4}"
+key() {
+    cd pdns-client
 
-    get_hooks "$DOMAIN" | while read LINE
+    if [ -f pdns.public.pem ]
+    then
+        cat pdns.public.pem
+    else
+        exit_error "No key present run init command first!"
+    fi
+}
+
+check_domain_precence() {
+    cat pdns-acme.json | jq -r '(.certs | to_entries[] | .key),(.certs[] | .alias | arrays | .[])' | while read domain
     do
-        $LINE
+        res=$(cat pdns-acme.json | jq .domains[\"$domain\"])
+        if [ $res == "null" ]
+        then
+            exit_error "No id configured for domain $domain"
+        fi
     done
 }
 
-exit_error() {
-  echo "ERROR: ${1}" >&2
-  exit 1
+cron() {
+    cat pdns-acme.json | jq -r '.certs | to_entries[] |
+        (.key + (if (.value.alias | length) > 0 then .value.alias | " " + join(" ") else "" end))' \
+    > dehydrated/domains.txt
+
+    echo 'CERTDIR="${BASEDIR}/../certs"' > dehydrated/config
+    echo 'HOOK_CHAIN="yes"' >> dehydrated/config
+    echo 'HOOK="${BASEDIR}/../hook"' >> dehydrated/config
+    echo 'CHALLENGETYPE="dns-01"' >> dehydrated/config
+
+    if [ -f dehydrated.config ]
+    then
+        cat dehydrated.config >> dehydrated/config
+    fi
+
+    cd dehydrated
+    ./dehydrated -c
+    cd ..
 }
 
-function resolv_config() {
-    if [ -f "pdns-acme.json" ]
+check_reqs() {
+    if [ ! -f "pdns-acme.json" ]
     then
-        CONFIG="pdns-acme.json"
-    elif [ -f "$SD/pdns-acme.json" ]
-    then
-        CONFIG="$SD/pdns-acme.json"
-    else
-        exit_error "Config file not found."
+        exit_error "No config file found!"
     fi
-    
-    if ! jq . "$CONFIG" >/dev/null 2>&1
-    then
-        exit_error "Parsing error in config file."
-    fi
-}
 
-function get_server() {
-    SERVER="$(jq -r .config.server $CONFIG)"
-    if [ "$SERVER" == "null" ]
+    if [ ! -f "pdns-client/pdns.public.pem" -o ! -f "pdns-client/pdns.private.pem" ]
     then
-        exit_error "No server supplied"
-    fi
-}
-
-function resolv_pdns_client() {
-    PDNSCLIENT="$(jq -r .config[\"pdns-client\"] $CONFIG)"
-    if [ "$PDNSCLIENT" == "null" ]
-    then
-        if [ -x "pdns-client" ]
-        then
-            PDNSCLIENT="pdns-client"
-        elif  [ -x "$SD/pdns-client" ]
-        then
-            PDNSCLIENT="$SD/pdns-client"
-        else
-            exit_error "PDNS Client not found."
-        fi
-    else
-        if [ -x "$PDNSCLIENT" ]
-        then
-            PDNSCLIENT="$PDNSCLIENT"
-        elif  [ -x "$SD/$PDNSCLIENT" ]
-        then
-            PDNSCLIENT="$SD/$PDNSCLIENT"
-        else
-            exit_error "PDNS Client not found."
-        fi
+        exit_error "No public key found, call 'pdns-acme init' first!"
     fi
 }
 
-function get_id() {
-    local ID="$(jq -r .domains[\"$1\"].id $CONFIG)"
-    if [ "$ID" == "null" ]
-    then
-        exit_error "No id for domain $1 supplied"
-    fi
-    echo "$ID"
-}
+SCRIPT=$(readlink -f "$0")
+SCRIPTPATH=$(dirname "$SCRIPT")
 
-function get_hooks() {
-    jq -r ".domains[\"$1\"].hook | (select(.>=[] and .<{}) | .[]), (select(.==tostring) | .)" $CONFIG
-}
+cd "$SCRIPTPATH"
 
-function get_sleep_time() {
-    SLEEP="$(jq -r .config[\"deploy-wait\"] $CONFIG)"
-    if [ "$SLEEP" == "null" ]
-    then
-        SLEEP=0 
-    fi
-}
-
-resolv_config
-get_server
-resolv_pdns_client
-get_sleep_time
-
-HANDLER=$1
-shift
-
-if [ "$HANDLER" = deploy_challenge ]
+if [ $# -lt 1 ]
 then
-    $HANDLER $@
-elif [ "$HANDLER" = clean_challenge ]
+    exit_error "Command init or cron required"
+elif [ $1 == "init" ]
 then
-    $HANDLER $@
-elif [ "$HANDLER" = deploy_cert ]
+    init
+elif [ $1 == "key" ]
 then
-    $HANDLER $@
+    key
+elif [ $1 == "cron" ]
+then
+    check_reqs
+    check_domain_precence
+    cron
 fi
-
-
